/**
 * ISO 4217 active currencies with a Spanish display name and a display
 * symbol — baked from `Intl.supportedValuesOf('currency')` +
 * `Intl.DisplayNames`/`Intl.NumberFormat` (narrow symbol, `en-US`) rather
 * than fetched from a network API: it's static reference data, so a
 * local list means the currency picker works offline and never depends on
 * a third-party service being up. Regenerate by re-running that same Intl
 * call if a new ISO currency is ever needed. Deprecated codes (e.g. SLL,
 * CUC) are excluded.
 */
export interface CurrencyMeta {
  /** ISO 4217 code, e.g. "MXN". */
  code: string;
  /** Spanish display name, e.g. "peso mexicano". */
  name: string;
  /** Display symbol, e.g. "$" — not unique across currencies. */
  symbol: string;
}

export const CURRENCIES: CurrencyMeta[] = [
  { code: "AFN", name: "afgani", symbol: "؋" },
  { code: "MGA", name: "ariari", symbol: "Ar" },
  { code: "PAB", name: "balboa panameño", symbol: "PAB" },
  { code: "THB", name: "bat", symbol: "฿" },
  { code: "ETB", name: "bir", symbol: "ETB" },
  { code: "VES", name: "bolívar venezolano", symbol: "VES" },
  { code: "BOB", name: "boliviano", symbol: "Bs" },
  { code: "GHS", name: "cedi", symbol: "GH₵" },
  { code: "KES", name: "chelín keniano", symbol: "KES" },
  { code: "SOS", name: "chelín somalí", symbol: "SOS" },
  { code: "TZS", name: "chelín tanzano", symbol: "TZS" },
  { code: "UGX", name: "chelín ugandés", symbol: "UGX" },
  { code: "CRC", name: "colón costarricense", symbol: "₡" },
  { code: "SVC", name: "colón salvadoreño", symbol: "SVC" },
  { code: "NIO", name: "córdoba oro", symbol: "C$" },
  { code: "CZK", name: "corona checa", symbol: "Kč" },
  { code: "DKK", name: "corona danesa", symbol: "kr" },
  { code: "ISK", name: "corona islandesa", symbol: "kr" },
  { code: "NOK", name: "corona noruega", symbol: "kr" },
  { code: "SEK", name: "corona sueca", symbol: "kr" },
  { code: "GMD", name: "dalasi", symbol: "GMD" },
  { code: "DZD", name: "dinar argelino", symbol: "DZD" },
  { code: "BHD", name: "dinar bareiní", symbol: "BHD" },
  { code: "IQD", name: "dinar iraquí", symbol: "IQD" },
  { code: "JOD", name: "dinar jordano", symbol: "JOD" },
  { code: "KWD", name: "dinar kuwaití", symbol: "KWD" },
  { code: "LYD", name: "dinar libio", symbol: "LYD" },
  { code: "MKD", name: "dinar macedonio", symbol: "MKD" },
  { code: "RSD", name: "dinar serbio", symbol: "RSD" },
  { code: "TND", name: "dinar tunecino", symbol: "TND" },
  { code: "AED", name: "dírham de los Emiratos Árabes Unidos", symbol: "AED" },
  { code: "MAD", name: "dírham marroquí", symbol: "MAD" },
  { code: "STN", name: "dobra", symbol: "Db" },
  { code: "AUD", name: "dólar australiano", symbol: "$" },
  { code: "BSD", name: "dólar bahameño", symbol: "$" },
  { code: "BBD", name: "dólar barbadense", symbol: "$" },
  { code: "BZD", name: "dólar beliceño", symbol: "$" },
  { code: "BMD", name: "dólar bermudeño", symbol: "$" },
  { code: "BND", name: "dólar bruneano", symbol: "$" },
  { code: "CAD", name: "dólar canadiense", symbol: "$" },
  { code: "KYD", name: "dólar de las Islas Caimán", symbol: "$" },
  { code: "TTD", name: "dólar de Trinidad y Tobago", symbol: "$" },
  { code: "XCD", name: "dólar del Caribe Oriental", symbol: "$" },
  { code: "USD", name: "dólar estadounidense", symbol: "$" },
  { code: "FJD", name: "dólar fiyiano", symbol: "$" },
  { code: "GYD", name: "dólar guyanés", symbol: "$" },
  { code: "HKD", name: "dólar hongkonés", symbol: "$" },
  { code: "JMD", name: "dólar jamaicano", symbol: "$" },
  { code: "LRD", name: "dólar liberiano", symbol: "$" },
  { code: "NAD", name: "dólar namibio", symbol: "$" },
  { code: "NZD", name: "dólar neozelandés", symbol: "$" },
  { code: "SBD", name: "dólar salomonense", symbol: "$" },
  { code: "SGD", name: "dólar singapurense", symbol: "$" },
  { code: "SRD", name: "dólar surinamés", symbol: "$" },
  { code: "ZWL", name: "dólar zimbabuense", symbol: "ZWL" },
  { code: "VND", name: "dong", symbol: "₫" },
  { code: "AMD", name: "dram", symbol: "֏" },
  { code: "CVE", name: "escudo de Cabo Verde", symbol: "CVE" },
  { code: "PLN", name: "esloti", symbol: "zł" },
  { code: "EUR", name: "euro", symbol: "€" },
  { code: "ANG", name: "florín antillano", symbol: "ANG" },
  { code: "AWG", name: "florín arubeño", symbol: "AWG" },
  { code: "HUF", name: "forinto húngaro", symbol: "Ft" },
  { code: "BIF", name: "franco burundés", symbol: "BIF" },
  { code: "XAF", name: "franco CFA de África Central", symbol: "FCFA" },
  { code: "XOF", name: "franco CFA de África Occidental", symbol: "F CFA" },
  { code: "XPF", name: "franco CFP", symbol: "CFPF" },
  { code: "KMF", name: "franco comorense", symbol: "CF" },
  { code: "CDF", name: "franco congoleño", symbol: "CDF" },
  { code: "GNF", name: "franco guineano", symbol: "FG" },
  { code: "RWF", name: "franco ruandés", symbol: "RF" },
  { code: "CHF", name: "franco suizo", symbol: "CHF" },
  { code: "DJF", name: "franco yibutiano", symbol: "DJF" },
  { code: "UAH", name: "grivna", symbol: "₴" },
  { code: "PYG", name: "guaraní paraguayo", symbol: "₲" },
  { code: "BTN", name: "gultrum", symbol: "BTN" },
  { code: "HTG", name: "gurde haitiano", symbol: "HTG" },
  { code: "MMK", name: "kiat", symbol: "K" },
  { code: "PGK", name: "kina", symbol: "PGK" },
  { code: "LAK", name: "kip", symbol: "₭" },
  { code: "MWK", name: "kuacha malauí", symbol: "MWK" },
  { code: "ZMW", name: "kuacha zambiano", symbol: "ZK" },
  { code: "AOA", name: "kuanza", symbol: "Kz" },
  { code: "HRK", name: "kuna", symbol: "kn" },
  { code: "GEL", name: "lari", symbol: "₾" },
  { code: "ALL", name: "lek", symbol: "ALL" },
  { code: "HNL", name: "lempira hondureño", symbol: "L" },
  { code: "SLE", name: "leona", symbol: "SLE" },
  { code: "MDL", name: "leu moldavo", symbol: "MDL" },
  { code: "RON", name: "leu rumano", symbol: "lei" },
  { code: "BGN", name: "leva búlgara", symbol: "BGN" },
  { code: "SHP", name: "libra de Santa Elena", symbol: "£" },
  { code: "EGP", name: "libra egipcia", symbol: "E£" },
  { code: "GBP", name: "libra esterlina", symbol: "£" },
  { code: "GIP", name: "libra gibraltareña", symbol: "£" },
  { code: "LBP", name: "libra libanesa", symbol: "L£" },
  { code: "FKP", name: "libra malvinense", symbol: "£" },
  { code: "SYP", name: "libra siria", symbol: "£" },
  { code: "SDG", name: "libra sudanesa", symbol: "SDG" },
  { code: "SSP", name: "libra sursudanesa", symbol: "£" },
  { code: "SZL", name: "lilangeni", symbol: "SZL" },
  { code: "TRY", name: "lira turca", symbol: "₺" },
  { code: "LSL", name: "loti lesotense", symbol: "LSL" },
  { code: "AZN", name: "manat azerbaiyano", symbol: "₼" },
  { code: "TMT", name: "manat turcomano", symbol: "TMT" },
  { code: "BAM", name: "marco convertible de Bosnia y Herzegovina", symbol: "KM" },
  { code: "MZN", name: "metical", symbol: "MZN" },
  { code: "NGN", name: "naira", symbol: "₦" },
  { code: "ERN", name: "nakfa", symbol: "ERN" },
  { code: "TWD", name: "nuevo dólar taiwanés", symbol: "$" },
  { code: "ILS", name: "nuevo séquel israelí", symbol: "₪" },
  { code: "TOP", name: "paanga", symbol: "T$" },
  { code: "MOP", name: "pataca de Macao", symbol: "MOP" },
  { code: "ARS", name: "peso argentino", symbol: "$" },
  { code: "CLP", name: "peso chileno", symbol: "$" },
  { code: "COP", name: "peso colombiano", symbol: "$" },
  { code: "CUP", name: "peso cubano", symbol: "$" },
  { code: "DOP", name: "peso dominicano", symbol: "$" },
  { code: "PHP", name: "peso filipino", symbol: "₱" },
  { code: "MXN", name: "peso mexicano", symbol: "$" },
  { code: "UYU", name: "peso uruguayo", symbol: "$" },
  { code: "BWP", name: "pula", symbol: "P" },
  { code: "GTQ", name: "quetzal guatemalteco", symbol: "Q" },
  { code: "ZAR", name: "rand", symbol: "R" },
  { code: "BRL", name: "real brasileño", symbol: "R$" },
  { code: "QAR", name: "rial catarí", symbol: "QAR" },
  { code: "IRR", name: "rial iraní", symbol: "IRR" },
  { code: "OMR", name: "rial omaní", symbol: "OMR" },
  { code: "SAR", name: "rial saudí", symbol: "SAR" },
  { code: "YER", name: "rial yemení", symbol: "YER" },
  { code: "KHR", name: "riel", symbol: "៛" },
  { code: "MYR", name: "ringit", symbol: "RM" },
  { code: "BYN", name: "rublo bielorruso", symbol: "BYN" },
  { code: "RUB", name: "rublo ruso", symbol: "₽" },
  { code: "MVR", name: "rufiya", symbol: "MVR" },
  { code: "LKR", name: "rupia esrilanquesa", symbol: "Rs" },
  { code: "INR", name: "rupia india", symbol: "₹" },
  { code: "IDR", name: "rupia indonesia", symbol: "Rp" },
  { code: "MUR", name: "rupia mauriciana", symbol: "Rs" },
  { code: "NPR", name: "rupia nepalí", symbol: "Rs" },
  { code: "PKR", name: "rupia pakistaní", symbol: "Rs" },
  { code: "SCR", name: "rupia seychellense", symbol: "SCR" },
  { code: "PEN", name: "sol peruano", symbol: "PEN" },
  { code: "KGS", name: "som", symbol: "⃀" },
  { code: "TJS", name: "somoni tayiko", symbol: "TJS" },
  { code: "UZS", name: "sum", symbol: "UZS" },
  { code: "BDT", name: "taka", symbol: "৳" },
  { code: "WST", name: "tala", symbol: "WST" },
  { code: "KZT", name: "tengue kazajo", symbol: "₸" },
  { code: "MNT", name: "tugrik", symbol: "₮" },
  { code: "MRU", name: "uguiya", symbol: "MRU" },
  { code: "VUV", name: "vatu", symbol: "VUV" },
  { code: "KPW", name: "won norcoreano", symbol: "₩" },
  { code: "KRW", name: "won surcoreano", symbol: "₩" },
  { code: "JPY", name: "yen", symbol: "¥" },
  { code: "CNY", name: "yuan", symbol: "¥" },
];

/** Looks up a currency's metadata by its ISO code, case-insensitive. */
export function findCurrency(code: string): CurrencyMeta | undefined {
  const upper = code.trim().toUpperCase();
  return CURRENCIES.find((c) => c.code === upper);
}
